---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:8.16.0
    commands:
      - npm ci
      - npm run build
    when:
      branch:
        - master
        - develop
